### ISSUE TITLE
Fix behaviour of media text blocks on small viewports

### ISSUE THREAD

**Issue by vdwijngaert** [WordCamp-Antwerp/styleguide-2020#6]
See current custom css:

```css
@media (max-width: 600px) {
	.wp-block-media-text.has-media-on-the-right {
		display: flex;
		flex-direction: column;
	}
	
	.wp-block-media-text__media {
		padding-bottom: 1rem;
	}
}
```
